/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, OwnableMsg, HexBinary, PostDispatchMsg, QueryMsg, OwnableQueryMsg, HookQueryMsg, AggregateHookQueryMsg, QuoteDispatchMsg, Addr, OwnerResponse, PendingOwnerResponse, HooksResponse, MailboxResponse, Uint128, QuoteDispatchResponse, Coin } from "./HookAggregate.types";
export interface HookAggregateMsg {
  contractAddress: string;
  sender: string;
  ownable: (ownableMsg: OwnableMsg, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  postDispatch: ({
    message,
    metadata
  }: {
    message: HexBinary;
    metadata: HexBinary;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setHooks: ({
    hooks
  }: {
    hooks: string[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class HookAggregateMsgComposer implements HookAggregateMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.ownable = this.ownable.bind(this);
    this.postDispatch = this.postDispatch.bind(this);
    this.setHooks = this.setHooks.bind(this);
  }

  ownable = (ownableMsg: OwnableMsg, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          ownable: ownableMsg
        })),
        funds: _funds
      })
    };
  };
  postDispatch = ({
    message,
    metadata
  }: {
    message: HexBinary;
    metadata: HexBinary;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          post_dispatch: {
            message,
            metadata
          }
        })),
        funds: _funds
      })
    };
  };
  setHooks = ({
    hooks
  }: {
    hooks: string[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_hooks: {
            hooks
          }
        })),
        funds: _funds
      })
    };
  };
}