/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  mailbox_code: number;
  origin_domain: number;
}
export type ExecuteMsg = {
  instantiate: {
    default_ism: string;
    owner: string;
  };
} | {
  migrate: {};
};
export type QueryMsg = {
  origin_domain: {};
};
export interface MigrateMsg {}
export interface OriginDomainResponse {
  domain: number;
}