/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./HookMerkle.types";
import * as _1 from "./HookMerkle.client";
import * as _2 from "./HookMerkle.message-composer";
import * as _3 from "./HookPausable.types";
import * as _4 from "./HookPausable.client";
import * as _5 from "./HookPausable.message-composer";
import * as _6 from "./HookRouting.types";
import * as _7 from "./HookRouting.client";
import * as _8 from "./HookRouting.message-composer";
import * as _9 from "./HookRoutingCustom.types";
import * as _10 from "./HookRoutingCustom.client";
import * as _11 from "./HookRoutingCustom.message-composer";
import * as _12 from "./HookRoutingFallback.types";
import * as _13 from "./HookRoutingFallback.client";
import * as _14 from "./HookRoutingFallback.message-composer";
import * as _15 from "./Igp.types";
import * as _16 from "./Igp.client";
import * as _17 from "./Igp.message-composer";
import * as _18 from "./IgpOracle.types";
import * as _19 from "./IgpOracle.client";
import * as _20 from "./IgpOracle.message-composer";
import * as _21 from "./IsmMultisig.types";
import * as _22 from "./IsmMultisig.client";
import * as _23 from "./IsmMultisig.message-composer";
import * as _24 from "./IsmRouting.types";
import * as _25 from "./IsmRouting.client";
import * as _26 from "./IsmRouting.message-composer";
import * as _27 from "./Mailbox.types";
import * as _28 from "./Mailbox.client";
import * as _29 from "./Mailbox.message-composer";
import * as _30 from "./ValidatorAnnounce.types";
import * as _31 from "./ValidatorAnnounce.client";
import * as _32 from "./ValidatorAnnounce.message-composer";
import * as _33 from "./WarpCw20.types";
import * as _34 from "./WarpCw20.client";
import * as _35 from "./WarpCw20.message-composer";
import * as _36 from "./WarpNative.types";
import * as _37 from "./WarpNative.client";
import * as _38 from "./WarpNative.message-composer";
export namespace contracts {
  export const HookMerkle = { ..._0,
    ..._1,
    ..._2
  };
  export const HookPausable = { ..._3,
    ..._4,
    ..._5
  };
  export const HookRouting = { ..._6,
    ..._7,
    ..._8
  };
  export const HookRoutingCustom = { ..._9,
    ..._10,
    ..._11
  };
  export const HookRoutingFallback = { ..._12,
    ..._13,
    ..._14
  };
  export const Igp = { ..._15,
    ..._16,
    ..._17
  };
  export const IgpOracle = { ..._18,
    ..._19,
    ..._20
  };
  export const IsmMultisig = { ..._21,
    ..._22,
    ..._23
  };
  export const IsmRouting = { ..._24,
    ..._25,
    ..._26
  };
  export const Mailbox = { ..._27,
    ..._28,
    ..._29
  };
  export const ValidatorAnnounce = { ..._30,
    ..._31,
    ..._32
  };
  export const WarpCw20 = { ..._33,
    ..._34,
    ..._35
  };
  export const WarpNative = { ..._36,
    ..._37,
    ..._38
  };
}