/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Hub.types";
import * as _1 from "./Hub.client";
import * as _2 from "./Hub.message-composer";
import * as _3 from "./IsmMultisig.types";
import * as _4 from "./IsmMultisig.client";
import * as _5 from "./IsmMultisig.message-composer";
import * as _6 from "./Mailbox.types";
import * as _7 from "./Mailbox.client";
import * as _8 from "./Mailbox.message-composer";
import * as _9 from "./Multicall.types";
import * as _10 from "./Multicall.client";
import * as _11 from "./Multicall.message-composer";
export namespace contracts {
  export const Hub = { ..._0,
    ..._1,
    ..._2
  };
  export const IsmMultisig = { ..._3,
    ..._4,
    ..._5
  };
  export const Mailbox = { ..._6,
    ..._7,
    ..._8
  };
  export const Multicall = { ..._9,
    ..._10,
    ..._11
  };
}