/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  hpl: string;
  owner: string;
  owner_pubkey: Binary;
}
export type ExecuteMsg = {
  update_owner: {
    owner: string;
    owner_pubkey: Binary;
  };
};
export type QueryMsg = "module_type" | {
  verify: {
    message: HexBinary;
    metadata: HexBinary;
  };
};
export type HexBinary = string;
export interface MigrateMsg {}
export type ModuleTypeResponse = ISMType;
export type ISMType = "unused" | "routing" | "aggregation" | "legacy_multisig" | "multisig" | "owned";
export type VerifyResponse = boolean;