/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, IsmSet, ExecuteMsg, OwnableMsg, QueryMsg, OwnableQueryMsg, IsmQueryMsg, HexBinary, RoutingIsmQueryMsg, Addr, OwnerResponse, PendingOwnerResponse, IsmType, ModuleTypeResponse, RouteResponse, VerifyResponse, VerifyInfoResponse } from "./IsmRouting.types";
export interface IsmRoutingReadOnlyInterface {
  contractAddress: string;
  ownable: (ownableQueryMsg: OwnableQueryMsg) => Promise<OwnableResponse>;
  ism: (ismQueryMsg: IsmQueryMsg) => Promise<IsmResponse>;
  routingIsm: (routingIsmQueryMsg: RoutingIsmQueryMsg) => Promise<RoutingIsmResponse>;
}
export class IsmRoutingQueryClient implements IsmRoutingReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.ownable = this.ownable.bind(this);
    this.ism = this.ism.bind(this);
    this.routingIsm = this.routingIsm.bind(this);
  }

  ownable = async (ownableQueryMsg: OwnableQueryMsg): Promise<OwnableResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownable: ownableQueryMsg
    });
  };
  ism = async (ismQueryMsg: IsmQueryMsg): Promise<IsmResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ism: ismQueryMsg
    });
  };
  routingIsm = async (routingIsmQueryMsg: RoutingIsmQueryMsg): Promise<RoutingIsmResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      routing_ism: routingIsmQueryMsg
    });
  };
}
export interface IsmRoutingInterface extends IsmRoutingReadOnlyInterface {
  contractAddress: string;
  sender: string;
  ownable: (ownableMsg: OwnableMsg, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  set: ({
    ism
  }: {
    ism: IsmSet;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class IsmRoutingClient extends IsmRoutingQueryClient implements IsmRoutingInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.ownable = this.ownable.bind(this);
    this.set = this.set.bind(this);
  }

  ownable = async (ownableMsg: OwnableMsg, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownable: ownableMsg
    }, fee, memo, _funds);
  };
  set = async ({
    ism
  }: {
    ism: IsmSet;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set: {
        ism
      }
    }, fee, memo, _funds);
  };
}