/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { OriginDomainResponse } from "./Hub.types";
export interface HubReadOnlyInterface {
    contractAddress: string;
    originDomain: () => Promise<OriginDomainResponse>;
}
export declare class HubQueryClient implements HubReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    originDomain: () => Promise<OriginDomainResponse>;
}
export interface HubInterface extends HubReadOnlyInterface {
    contractAddress: string;
    sender: string;
    instantiate: ({ defaultIsm, owner }: {
        defaultIsm: string;
        owner: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    migrate: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class HubClient extends HubQueryClient implements HubInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    instantiate: ({ defaultIsm, owner }: {
        defaultIsm: string;
        owner: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    migrate: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
//# sourceMappingURL=Hub.client.d.ts.map