/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
export interface HubMessage {
    contractAddress: string;
    sender: string;
    instantiate: ({ defaultIsm, owner }: {
        defaultIsm: string;
        owner: string;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    migrate: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class HubMessageComposer implements HubMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    instantiate: ({ defaultIsm, owner }: {
        defaultIsm: string;
        owner: string;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    migrate: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
//# sourceMappingURL=Hub.message-composer.d.ts.map