/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Hub.client";
import * as _2 from "./Hub.message-composer";
import * as _4 from "./IsmMultisig.client";
import * as _5 from "./IsmMultisig.message-composer";
import * as _7 from "./Mailbox.client";
import * as _8 from "./Mailbox.message-composer";
import * as _10 from "./Multicall.client";
import * as _11 from "./Multicall.message-composer";
export declare namespace contracts {
    const Hub: {
        HubMessageComposer: typeof _2.HubMessageComposer;
        HubQueryClient: typeof _1.HubQueryClient;
        HubClient: typeof _1.HubClient;
    };
    const IsmMultisig: {
        IsmMultisigMessageComposer: typeof _5.IsmMultisigMessageComposer;
        IsmMultisigQueryClient: typeof _4.IsmMultisigQueryClient;
        IsmMultisigClient: typeof _4.IsmMultisigClient;
    };
    const Mailbox: {
        MailboxMessageComposer: typeof _8.MailboxMessageComposer;
        MailboxQueryClient: typeof _7.MailboxQueryClient;
        MailboxClient: typeof _7.MailboxClient;
    };
    const Multicall: {
        MulticallMessageComposer: typeof _11.MulticallMessageComposer;
        MulticallQueryClient: typeof _10.MulticallQueryClient;
        MulticallClient: typeof _10.MulticallClient;
    };
}
//# sourceMappingURL=index.d.ts.map