/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export interface InstantiateMsg {
    chain_hpl: string;
    owner: string;
}
export type ExecuteMsg = {
    enroll_validator: {
        set: ValidatorSet;
    };
} | {
    enroll_validators: {
        set: ValidatorSet[];
    };
} | {
    unenroll_validator: {
        domain: number;
        validator: string;
    };
} | {
    set_threshold: {
        set: ThresholdSet;
    };
} | {
    set_thresholds: {
        set: ThresholdSet[];
    };
} | {
    init_transfer_ownership: {
        owner: string;
    };
} | {
    finish_transfer_ownership: [];
} | {
    revoke_transfer_ownership: [];
};
export type Binary = string;
export interface ValidatorSet {
    domain: number;
    validator: string;
    validator_pubkey: Binary;
}
export interface ThresholdSet {
    domain: number;
    threshold: number;
}
export type QueryMsg = {
    module_type: {};
} | {
    verify: {
        message: HexBinary;
        metadata: HexBinary;
    };
};
export type HexBinary = string;
export interface MigrateMsg {
}
export type ISMType = "unused" | "routing" | "aggregation" | "legacy_multisig" | "multisig" | "owned";
export interface ModuleTypeResponse {
    type: ISMType;
}
export interface VerifyResponse {
    verified: boolean;
}
//# sourceMappingURL=IsmMultisig.types.d.ts.map