/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export interface InstantiateMsg {
    default_ism: string;
    owner: string;
}
export type ExecuteMsg = {
    pause: {};
} | {
    unpause: {};
} | {
    set_default_i_s_m: {
        ism: string;
    };
} | {
    dispatch: {
        dest_domain: number;
        msg_body: HexBinary;
        recipient_addr: HexBinary;
    };
} | {
    process: {
        message: HexBinary;
        metadata: HexBinary;
    };
};
export type HexBinary = string;
export type QueryMsg = {
    root: {};
} | {
    count: {};
} | {
    check_point: {};
} | {
    paused: {};
} | {
    nonce: {};
};
export interface MigrateMsg {
}
export interface CheckPointResponse {
    count: number;
    root: HexBinary;
}
export interface CountResponse {
    count: number;
}
export interface NonceResponse {
    nonce: number;
}
export interface PausedResponse {
    paused: boolean;
}
export interface RootResponse {
    root: HexBinary;
}
//# sourceMappingURL=Mailbox.types.d.ts.map