/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { CosmosMsgForEmpty, Coin, HandleMsg } from "./Multicall.types";
export interface MulticallMessage {
    contractAddress: string;
    sender: string;
    aggregate: ({ req }: {
        req: CosmosMsgForEmpty[];
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    handle: ({ msg }: {
        msg: HandleMsg;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class MulticallMessageComposer implements MulticallMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    aggregate: ({ req }: {
        req: CosmosMsgForEmpty[];
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    handle: ({ msg }: {
        msg: HandleMsg;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
//# sourceMappingURL=Multicall.message-composer.d.ts.map